version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db_shortener'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'db_password'
      MYSQL_ROOT_PASSWORD: 'db_password'
    restart: always
    volumes:
      - ../docker_volumes/db_shortener:/var/lib/mysql
  web:
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db
    restart: always
  redis:
    image: redis:alpine
    volumes:
      - ../docker_volumes/redis:/var/lib/mysql
  celery:
    restart: always
    build:
      context: .
    command: celery -A config worker -B
    depends_on:
      - redis
      - web