# Generated by Django 3.1.7 on 2021-03-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255, verbose_name='Session key')),
                ('url', models.URLField(max_length=3000, verbose_name='Original URL')),
                ('short_url', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Short URL')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
